name: futsmandu_flutter
description: A Flutter app for Futsmandu court booking system
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP & API
  dio: ^5.4.0

  # State Management
  provider: ^6.1.1

  # Local Storage
  shared_preferences: ^2.2.2

  # Navigation
  go_router: ^13.0.0

  image_picker: ^1.0.7

  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1

  # Utilities
  intl: ^0.19.0
  equatable: ^2.0.5

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.7
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4 

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/logo/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/futsmandu_logo.png"
  adaptive_icon_background: "#1E7F1E"
  remove_alpha_ios: true